#!/bin/bash

# URlS that are commented out have been completed



# These are the android repos that will be cloned
# the format is
# AREPO[URL num - 1]

 AREPO[0]=git://android.git.kernel.org/platform/build.git
 AREPO[1]=git://android.git.kernel.org/platform/frameworks/base.git
 AREPO[2]=git://android.git.kernel.org/platform/hardware/qcom/gps.git
 AREPO[3]=git://android.git.kernel.org/platform/packages/apps/Settings.git
 AREPO[4]=git://android.git.kernel.org/platform/hardware/msm7k.git
# AREPO[5]=git://android.git.kernel.org/platform/packages/apps/Settings.git
# AREPO[6]=git://android.git.kernel.org/platform/packages/apps/Settings.git


#git://android.git.kernel.org/platform/dalvik.git
#git://android.git.kernel.org/platform/bionic.git
#git://android.git.kernel.org/platform/build.git

# These are the github repos that will be cloned
# the format is
# GREPO[URL num - 1]

 GREPO[0]=git@github.com:ConicalRom/platform_build.git
 GREPO[1]=git@github.com:ConicalRom/platform_frameworks_base.git
 GREPO[2]=git@github.com:ConicalRom/platform_hardware_qcom_gps.git
 GREPO[3]=git@github.com:ConicalRom/platform_packages_apps_settings.git
 GREPO[4]=git@github.com:ConicalRom/platform_hardware_msm7k.git
# GREPO[5]=git@github.com:ConicalRom/android_device_htc_inc.git
# GREPO[6]=git@github.com:ConicalRom/android_device_htc_inc.git




echo 'Press to begin the process'
read IN

# the number to loop to
# The loop number should be the same as the url number
for I in {0..5}
do
echo 'cloning'
git clone ${AREPO[$I]} tmp$I
cd tmp$I
echo 'Adding remotes '${GREPO[$I]}
git remote add github ${GREPO[$I]} 
git remote -v

echo 'fetching remotes'
git fetch origin gingerbread
git fetch github

echo 'Creating local branches from github'
git checkout github/master 
git checkout -b toupdate 

echo 'Creating local branches from android.kernel.git or whatever it is'
git checkout origin/gingerbread 
git checkout -b updates

git checkout toupdate



echo 'We are about to rebase please press enter to begin'
read IN


git rebase -i -m -s=ours updates

echo 'Here is a terminal. First start the meld editor after the rebase has started, then after melding continue the rebase'
echo 'If the rebase cannot complete you can use the provided terminal to merge to the desired branch'
echo 'Please close the terminal to continue'
DIR=`pwd`

gnome-terminal --working-directory=$DIR



echo 'and press enter when you are done rebasing/merging'
read IN
git checkout -b updating
git push github updating

cd ..

done
