#!/bin/bash

# URlS that are commented out have been completed

# These are the android repos that will be cloned
# the format is
# AREPO[URL num - 1]

# AREPO[0]=git://android.git.kernel.org/platform/packages/providers/MediaProvider.git
# AREPO[1]=git://android.git.kernel.org/platform/packages/apps/Settings.git
# AREPO[2]=git://android.git.kernel.org/platform/packages/apps/Launcher2.git
# AREPO[3]=git://android.git.kernel.org/platform/packages/apps/Phone.git
# AREPO[4]=git://android.git.kernel.org/platform/packages/apps/Music.git
# AREPO[5]=git://android.git.kernel.org/platform/system/extras.git
# AREPO[6]=git://android.git.kernel.org/platform/system/core.git
AREPO[7]=git://android.git.kernel.org/platform/external/dhcpcd.git
# AREPO[8]=git://android.git.kernel.org/platform/external/wpa_supplicant.git
# AREPO[9]=git://android.git.kernel.org/platform/external/wpa_supplicant_6.git
# AREPO[10]=git://android.git.kernel.org/platform/frameworks/base.git

#git://android.git.kernel.org/platform/dalvik.git
#git://android.git.kernel.org/platform/bionic.git
#git://android.git.kernel.org/platform/build.git

# These are the github repos that will be cloned
# the format is
# GREPO[URL num - 1]

# GREPO[0]=git@github.com:OMFGB/android_packages_providers_MediaProvider.git
# GREPO[1]=git@github.com:OMFGB/android_packages_apps_Settings.git
# GREPO[2]=git@github.com:OMFGB/android_packages_apps_Launcher2.git
# GREPO[3]=git@github.com:OMFGB/android_packages_apps_Phone.git
# GREPO[4]=git@github.com:OMFGB/android_packages_apps_Music.git
# GREPO[5]=git@github.com:OMFGB/android_system_extras.git
# GREPO[6]=git@github.com:OMFGB/android_system_core.git
GREPO[7]=git@github.com:OMFGB/android_system/external/dhcpcd.git
# GREPO[8]=git@github.com:OMFGB/android_external_wpa_supplicant.git
# GREPO[9]=git@github.com:OMFGB/android_external_wpa_supplicant_6.git
# GREPO[10]=git@github.com:OMFGB/android_frameworks_base.git
#git@github.com:OMFGB/android_dalvik.git
#git@github.com:OMFGB/android_bionic.git
#git@github.com:OMFGB/android_build.git



echo 'Press to begin the process'
read IN

# the number to loop to
# The loop number should be the same as the url number
for I in {7..7}
do
echo 'cloning'
git clone ${AREPO[$I]} tmp$I
cd tmp$I
echo 'Adding remotes '${GREPO[$I]}
git remote add github ${GREPO[$I]} 
git remote -v

echo 'fetching remotes'
git fetch origin gingerbread
git fetch github

echo 'Creating local branches from github'
git checkout github/master 
git checkout -b toupdate 

echo 'Creating local branches from android.kernel.git or whatever it is'
git checkout origin/gingerbread 
git checkout -b updates

git checkout toupdate



echo 'We are about to rebase please press enter to begin'
read IN


git rebase -i -m -s=ours updates

echo 'Here are two terminals, one to continue the rebasing one to start the meld editor after the rebase has started'
DIR=`pwd`

gnome-terminal --working-directory=$DIR


echo 'Please close the terminal to continue'
echo 'and press enter when you are done rebasing'
read IN
git checkout -b updating
git push github updating

cd ..

done
